//
//  ProkopeAppDelegate.m
//  Prokope
//
//  Created by D. Robert Adams on 5/9/11.
//  Copyright 2011 Grand Valley State University. All rights reserved.
//

#import "ProkopeAppDelegate.h"
#import "ProkopeViewController.h"
#import "Author.h"
#import "Work.h"

@implementation ProkopeAppDelegate

@synthesize window;
@synthesize viewController;


#pragma mark -
#pragma mark Application lifecycle

/******************************************************************************
 * This method is called when the application first begins to launch.
 */
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {    
 	
    // Override point for customization after app launch.
	
	// This line initialized the navigation controller. 
	ProkopeNavigationController = [[UINavigationController alloc] init];
	
	[window addSubview:ProkopeNavigationController.view];
	
	viewController = [[ProkopeViewController alloc] initWithNibName:@"ProkopeViewController" bundle:nil];
	
	UIBarButtonItem *anotherButton = [[UIBarButtonItem alloc] initWithTitle:@"Prokope" style:UIBarButtonItemStylePlain target:nil action:nil];          
	viewController.navigationItem.backBarButtonItem = anotherButton;
	[anotherButton release];
	
	[ProkopeNavigationController pushViewController:viewController animated:NO];
	[viewController release];
	
    [self.window makeKeyAndVisible];
	
	return YES;
}

/******************************************************************************
 * This method is used by the NSXMLParserDelegate protocol and it populates all
 * the data from the XML file. The data is populated with Authors, Works, and
 * Chapters using NSMutableArrays for each of these XML tags.
 */
- (void)parser:(NSXMLParser *)parser didStartElement:(NSString *)elementName 
  namespaceURI:(NSString *)namespaceURI qualifiedName:(NSString *)qualifiedName 
	attributes:(NSDictionary *)attributeDict
{
	
}

/******************************************************************************
 * This method is part of the NSXMLParserDelegate protocol. Whenever there is 
 * data found between the XML tags this method is called. This is part of the 
 * event driven parser model that the i-phone gives us.
 */
- (void)parser:(NSXMLParser *)parser foundCharacters:(NSString *)string
{

}
		 
/******************************************************************************
 * This method is used by the NSXMLParserDelegate protocol and it keeps track of
 * what the current author and work are. 
 */
- (void)parser:(NSXMLParser *)parser didEndElement:(NSString *)elementName 
  namespaceURI:(NSString *)namespaceURI qualifiedName:(NSString *)qName
{

}

/******************************************************************************
 * This is an autogenerated method.
 */
- (void)applicationWillResignActive:(UIApplication *)application
{
    /*
     Sent when the application is about to move from active to inactive state. This can occur for certain types of temporary interruptions (such as an incoming phone call or SMS message) or when the user quits the application and it begins the transition to the background state.
     Use this method to pause ongoing tasks, disable timers, and throttle down OpenGL ES frame rates. Games should use this method to pause the game.
     */
}

/******************************************************************************
 * This is an autogenerated method.
 */
- (void)applicationDidBecomeActive:(UIApplication *)application
{
    /*
     Restart any tasks that were paused (or not yet started) while the application was inactive. If the application was previously in the background, optionally refresh the user interface.
     */
}

/******************************************************************************
 * This is an autogenerated method.
 */
- (void)applicationWillTerminate:(UIApplication *)application
{

}


#pragma mark -
#pragma mark Memory management

- (void)applicationDidReceiveMemoryWarning:(UIApplication *)application
{
    /*
     Free up as much memory as possible by purging cached data objects that can be recreated (or reloaded from disk) later.
     */
}

/******************************************************************************
 * This clears up our memory.
 */
- (void)dealloc
{
    [viewController release];
    [window release];
//	[AuthorsArray release];
    [super dealloc];
}





@end
